package com.ospreydcs.dp.gui.component;

import com.ospreydcs.dp.grpc.v1.common.Attribute;
import com.ospreydcs.dp.grpc.v1.common.ColumnMetadata;
import com.ospreydcs.dp.grpc.v1.common.ColumnProvenance;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;
import javafx.collections.ObservableList;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.control.TextField;
import javafx.scene.layout.VBox;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.ResourceBundle;

/**
 * Reusable component for the Column Metadata section.
 * Contains column provenance (source and process), tags, and attributes.
 *
 * The values entered here are applied uniformly to every column in the DataFrame(s) of the
 * IngestDataRequest(s) generated by the containing view.
 */
public class ColumnMetadataComponent extends VBox implements Initializable {

    private static final Logger logger = LogManager.getLogger();

    // FXML components
    @FXML private TextField provenanceSourceField;
    @FXML private TextField provenanceProcessField;
    @FXML private TagsListComponent columnTagsComponent;
    @FXML private AttributesListComponent columnAttributesComponent;

    // Properties for external binding
    private final StringProperty provenanceSource = new SimpleStringProperty();
    private final StringProperty provenanceProcess = new SimpleStringProperty();

    public ColumnMetadataComponent() {
        // Load FXML and set this as controller
        FXMLLoader fxmlLoader = new FXMLLoader(getClass().getResource("/fxml/components/column-metadata-component.fxml"));
        fxmlLoader.setController(this);

        try {
            VBox root = fxmlLoader.load();
            this.getChildren().setAll(root.getChildren());
            this.setSpacing(root.getSpacing());
            this.setPadding(root.getPadding());
            this.getStyleClass().setAll(root.getStyleClass());
        } catch (IOException exception) {
            logger.error("Failed to load ColumnMetadataComponent FXML", exception);
            throw new RuntimeException(exception);
        }
    }

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        logger.debug("ColumnMetadataComponent initialized");

        // Bind provenance fields to properties
        provenanceSourceField.textProperty().bindBidirectional(provenanceSource);
        provenanceProcessField.textProperty().bindBidirectional(provenanceProcess);

        logger.debug("ColumnMetadataComponent setup complete");
    }

    // Public API methods for external access

    /**
     * Gets the provenance source.
     */
    public String getProvenanceSource() {
        return provenanceSource.get();
    }

    /**
     * Sets the provenance source.
     */
    public void setProvenanceSource(String provenanceSource) {
        this.provenanceSource.set(provenanceSource);
    }

    /**
     * Property for provenance source binding.
     */
    public StringProperty provenanceSourceProperty() {
        return provenanceSource;
    }

    /**
     * Gets the provenance process.
     */
    public String getProvenanceProcess() {
        return provenanceProcess.get();
    }

    /**
     * Sets the provenance process.
     */
    public void setProvenanceProcess(String provenanceProcess) {
        this.provenanceProcess.set(provenanceProcess);
    }

    /**
     * Property for provenance process binding.
     */
    public StringProperty provenanceProcessProperty() {
        return provenanceProcess;
    }

    /**
     * Gets the column tags list.
     */
    public ObservableList<String> getColumnTags() {
        return columnTagsComponent.getTags();
    }

    /**
     * Sets the column tags list.
     */
    public void setColumnTags(ObservableList<String> tags) {
        columnTagsComponent.setTags(tags);
    }

    /**
     * Gets the column attributes list, with each entry in "key=value" form.
     */
    public ObservableList<String> getColumnAttributes() {
        return columnAttributesComponent.getAttributes();
    }

    /**
     * Sets the column attributes list.
     */
    public void setColumnAttributes(ObservableList<String> attributes) {
        columnAttributesComponent.setAttributes(attributes);
    }

    /**
     * Builds a ColumnMetadata message from the current contents of the component, to be applied to
     * each column of the ingestion request.
     *
     * Returns null if no metadata has been entered, so that the columns are sent without a metadata
     * field rather than with an empty one.  Unset provenance fields are omitted rather than sent as
     * empty strings, per the ColumnProvenance contract in common.proto.
     *
     * NOTE: the provenance blank-check and omit-empty rules below intentionally mirror
     * IngestionClient.IngestionRequestParams.setColumnMetadata(source, process, tags, attributes)
     * in dp-service.  That overload always builds a metadata message, so it cannot express the
     * "nothing entered, send no metadata field at all" case this component needs.  If the
     * ColumnProvenance contract in common.proto changes, both copies must be updated.
     */
    public ColumnMetadata getColumnMetadata() {

        final String source = getProvenanceSource();
        final String process = getProvenanceProcess();
        final ObservableList<String> tags = getColumnTags();
        final ObservableList<String> attributes = getColumnAttributes();

        final boolean hasSource = source != null && !source.isBlank();
        final boolean hasProcess = process != null && !process.isBlank();
        final boolean hasTags = tags != null && !tags.isEmpty();

        // Only attributes that parse to a non-blank key are usable.  The add form prevents malformed
        // entries, but setColumnAttributes() accepts an arbitrary list, and getKeyFromAttribute()
        // returns the whole string when there is no "=" separator.
        final List<String> validAttributes = new ArrayList<>();
        if (attributes != null) {
            for (String attribute : attributes) {
                final String key = AttributesListComponent.getKeyFromAttribute(attribute);
                if (key != null && !key.isBlank()) {
                    validAttributes.add(attribute);
                } else {
                    logger.warn("ignoring column attribute with blank key: {}", attribute);
                }
            }
        }
        final boolean hasAttributes = !validAttributes.isEmpty();

        if (!hasSource && !hasProcess && !hasTags && !hasAttributes) {
            logger.debug("no column metadata specified");
            return null;
        }

        final ColumnMetadata.Builder metadataBuilder = ColumnMetadata.newBuilder();

        if (hasSource || hasProcess) {
            final ColumnProvenance.Builder provenanceBuilder = ColumnProvenance.newBuilder();
            if (hasSource) {
                provenanceBuilder.setSource(source.trim());
            }
            if (hasProcess) {
                provenanceBuilder.setProcess(process.trim());
            }
            metadataBuilder.setProvenance(provenanceBuilder.build());
        }

        if (hasTags) {
            metadataBuilder.addAllTags(tags);
        }

        for (String attribute : validAttributes) {
            final String key = AttributesListComponent.getKeyFromAttribute(attribute);
            final String value = AttributesListComponent.getValueFromAttribute(attribute);
            metadataBuilder.addAttributes(
                    Attribute.newBuilder().setName(key.trim()).setValue(value).build());
        }

        final ColumnMetadata columnMetadata = metadataBuilder.build();
        logger.debug(
                "built column metadata, provenance: {}, tags: {}, attributes: {}",
                columnMetadata.hasProvenance(),
                columnMetadata.getTagsCount(),
                columnMetadata.getAttributesCount());

        return columnMetadata;
    }

    /**
     * Clears all column metadata.
     */
    public void clearColumnMetadata() {
        setProvenanceSource("");
        setProvenanceProcess("");
        columnTagsComponent.clearTags();
        columnAttributesComponent.clearAttributes();
        logger.debug("Column metadata cleared");
    }
}
